### DISCUSSION TITLE
Have some hierarchy in packages names

### DISCUSSION THREAD

**Discussion by rberger** [thomvaill/log4brains#73] [Feedback]
Be nice to be able to have hierarchy in the package names. For instance would like to have the following file layout in a mono-repo:

apps- |
            app0
            app1

infrastructure -|
                          terraform

Right now I can say in my log4brains.yml:

```
project:
  name: techno-core
  tz: America/Los_Angeles
  adrFolder: ./
  packages:
    - name: infrastructure
      path: ./infrastructure
      adrFolder: ./infrastructure
    - name: app0
      path: ./apps/app0
      adrFolder: ./apps/app0
    - name: app1
      path: ./apps/app1
      adrFolder: ./apps/app1
```

I can do a `log4brains add new` and specify the package as infrastructure, app0 or app1

But I would like to be able to specify the app name with a path like `apps/app0` and `infrastructure/terraform`

The current implementation won't allow slashes in the app name. Would rather not use dashes as we have application names with dashes (well really underscores but that's another issue, log4brains won't allow underscores in the package name)
