### ISSUE TITLE
Using superseded adrs with multi package project.

### ISSUE THREAD

**Issue by mesuutt** [thomvaill/log4brains#107]
# Bug Report

## Description

We want to use superseded adrs.
We updated `Status` of the superseded doc like below:

```txt
- Status: superseded by [20201029-superseder](20201029-superseder.md)
```
And we added link to superseded doc in superseder doc like below:

```txt
- Supersedes [20201028-superseded-adr](20201028-superseded-adr.md)
```

When we clicked to superseded adr from adr list it returns 500 response and we got `Error: You forgot to pass the superseder
` error from terminal.

## Steps to Reproduce

```
project:
  name: my adrs
  tz: Europe/Istanbul
  packages:
    - name: mypackage
      path: ./mypackage
      adrFolder: ./mypackage/docs/adr
```

Directory structure is like below:
```
.
├── mypackage
│ ├── docs
│ │ └── adr
│ │     ├── 20201028-superseded-adr.md
│ │     └── 20201029-superseder.md
```

## Expected Behavior

Superseded ADRs in multi package project should be work like mono package project.
We tried with mono package structure and it worked like expected.

## Context

We want to create ADRs in multi package project structure.

## Environment

- Log4brains version: 1.0.1
- Node.js version: v19.6.0
- OS and its version: MacOs Darwin 22.4.0 Darwin Kernel Version 22.4.0:
