### ISSUE TITLE
Add howto for non-npm projects

### ISSUE THREAD

**Issue by koppor** [thomvaill/log4brains#14]
I want to collect all available ADRs.

I place following yml file in my repo

```yml
project:
  repository:
    url: https://git.example.com/org/project
    provider: github
    adrFolder: ./subproject/docs/adr
```

I run

    $ log4brains-web build

I get following output:

```
Building Log4brains...
info  - Creating an optimized production build
```

However, the folder is still empty:

```
$ dir
...

22.12.2020  11:38    <DIR>          .
22.12.2020  11:38    <DIR>          ..
22.12.2020  11:38                 0 .gitignore
22.12.2020  11:40               139 .log4brains.yml
22.12.2020  10:16               293 README.md
               3 Datei(en),            432 Bytes
...
```

Is it possible to provide some more output to enable debugging the usage?

Oliver Kopp <oliver.kopp@mbition.io>, Mercedes-Benz AG on behalf of [MBition GmbH](https://mbition.io/).

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)
