### ISSUE TITLE
it doesn't works in GitlabCI (no errors)

### ISSUE THREAD

**Issue by jalberto** [thomvaill/log4brains#26]
# Bug Report

## Description

`build` doesn't work in CI

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/99927/108204032-90ad4280-7123-11eb-8837-95e5f5a41c7c.png)

## Expected Behavior

to build correctly or at least display errors

**Comment by thomvaill** [comment]
Hi @jalberto 

Sorry for the late fix!

You just have to add `--unsafe-perm` to the `npm install` command on GitLab, because it is executed as root.
I updated the README accordingly. The example configuration is now:

```yml
image: node:14-alpine3.12
pages:
  stage: deploy
  variables:
    GIT_DEPTH: 0 # required by Log4brains to work correctly (needs the whole Git history)
  script:
    - mkdir -p public
    - npm install -g --unsafe-perm log4brains
    - log4brains build --basePath /$CI_PROJECT_NAME/log4brains --out public/log4brains
  artifacts:
    paths:
      - public
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
```

I also improved the error logging: all the Next.js errors were trapped for the `log4brains build` command (see https://github.com/thomvaill/log4brains/pull/34)

Thank you!
