### ISSUE TITLE
Support local images

### ISSUE THREAD

**Issue by thomvaill** [thomvaill/log4brains#4]
# Feature Request

## Feature Suggestion

Log4brains should be able to serve local images that are displayed in the markdown files.

## Possible Implementation 

Have a look at [next/image](https://nextjs.org/docs/api-reference/next/image)

**Comment by alexsuter** [comment]
Great project, love it! I really would appreciate this feature.

**Comment by poznachowski** [comment]
I second that. This looks awesome, really good work! However, not being able to easily serve local images is a blocker for proceeding with log4brains to me.

**Comment by szymonbohdanowicz** [comment]
@thomvaill any progress with this feature? such an option would be really helpful for us

**Comment by thomvaill** [comment]
I started working on it last December, I've almost finished the feature but unfortunately, but I still have some issues to solve.
I hope I will be able to release it soon. I'll keep you informed

**Comment by mengano-net** [comment]
@thomvaill Great project, thanks!

**Comment by snowron** [comment]
@thomvaill dear thomas, i want to solve this issue and want to start development. what do you think?

**Comment by thomvaill** [comment]
Hi all.
FYI I finished about 90% of the dev of this feature. However I move this issue into the milestone v1.2.0 because I'd like to tackle these important topics first: https://github.com/thomvaill/log4brains/discussions/108#discussioncomment-10768555

**Comment by barseghyanartur** [comment]
This is how I use it:

----

# Log4Brains images support

## Directory structure

```
docs
├── adr
│   ├── 20240416-architecture-v2.md
│   ├── 20240916-llm-choice.md
│   ├── 20240916-rag-framework-choice.md
│   ├── index.md
│   └── template.md
└── l4b-static
    └── images
        ├── favicon-16x16.png
        └── favicon-32x32.png
```

## Makefile

*Filename: Makefile*

```
add-adr:
    docker run --rm -ti -v $$(pwd):/workdir -p 4004:4004 thomvaill/log4brains adr new $(ARGS)

preview:
    docker run --rm -ti -v $$(pwd):/workdir -p 4004:4004 thomvaill/log4brains preview $(ARGS)

build:
    docker run --rm -ti -v $$(pwd):/workdir -p 4004:4004 thomvaill/log4brains build $(ARGS)
    cp -R docs/l4b-static/* .log4brains/out/l4b-static/

# Serve the built docs on port 5002
serve:
    cd .log4brains/out && python3 -m http.server 5002
```

## GitHub Action

*Filename: .github/workflows/publish-log4brains.yml*

```yaml
name: Publish Log4brains
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # required by JamesIves/github-pages-deploy-action
          fetch-depth: 0 # required by Log4brains to work correctly (needs the whole Git history)
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install and Build Log4brains
        run: |
          npm install -g log4brains
          log4brains build
          cp -R docs/l4b-static/* .log4brains/out/l4b-static/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .log4brains/out
```

## Usage example

*Filename: docs/adr/index.md*

```markdown
# Architecture knowledge base

Welcome 👋 to the architecture knowledge base of Project ![Project](/l4b-static/images/favicon-16x16.png).
You will find here all the Architecture Decision Records (ADR) of the project.
```
